### ISSUE TITLE
Replace Bing by Google Option

### ISSUE THREAD

**Issue by brunocalado** [SvenWerlen/moulinette-imagesearch#1]
Hi.

You did an amazing work.

Can you add an option to replace Bing by Google?

Thank you.

**Comment by SvenWerlen** [comment]
Thanks for your comments!
The problem with search capabilities is that APIs are not free to use. 
Google search is about 5$/1000 req. The first 100 req/day are free.
I'll eventually propose Google as alternate search but I must think about how to protect myself against too heavy usage.

**Comment by Shuggaloaf** [comment]
Thanks for the great mods Sven. 

I also hope you figure out a way to offer an alternative. Preferably one without the extensive signup process that Microsoft currently requires. Some people do no have a credit card or "non-VOIP" phone to give to Microsoft. Beyond that, many of us do not _want_ to give Microsoft (or other data-mining companies) any information.

Please do not take that as criticism towards you, I understand your difficulties. This is just to express user viewpoints (that I'm guessing others share). 

Either way, great work on the mod suite!

**Comment by SvenWerlen** [comment]
I implemented the integration with Google Search API. 
See : https://www.patreon.com/posts/image-search-72427626

However, it still requires an extensive signup process (but with Google Cloud).
Unfortunately, those APIs are not available without signup and API keys.
Openverse is the only exception but search results are limited to Creative Commons images.
