### ISSUE TITLE
Allow Creative Commons search

### ISSUE THREAD

**Issue by akrigline** [SvenWerlen/moulinette-imagesearch#3]
https://opensource.creativecommons.org/archives/cc-search/

Since this is pretty parallel to what imagesearch already does, I figured I'd ask if you were interested in what this League trello card is after:

https://trello.com/c/x5WhyLN6/164-creative-commons-catalog-integration

Ideally one would allow the user to toggle to only search the Creative Commons library, or to search both bing and the CC library.

**Comment by SvenWerlen** [comment]
Hi,
Thank you for proposing this. This is the next task on my list.

**Comment by SvenWerlen** [comment]
Here it is. Implemented in version `1.4.0`
![Screenshot_20210508_171711](https://user-images.githubusercontent.com/938060/117553747-3c7a7600-b021-11eb-8419-9ae898547650.png)
