### ISSUE TITLE
cx censoring failed

### ISSUE THREAD

**Issue by rapus95** [SvenWerlen/moulinette-imagesearch#6]
in your image https://github.com/SvenWerlen/moulinette-imagesearch/blob/main/docs/img/configure-google-engine.jpg you censored the cx but not the public url which also contains your cx id. Given it's the public url, having that leaked is probably no problem, but just in case you don't want it, take this as notification.

**Comment by SvenWerlen** [comment]
Hi @rapus95, thank you for reporting this!
You're absolutely right. I should have blurred it, too (even if I don't know if that information is sensible or not).
Anyway, I deleted the engine to avoid any security issue.
I fixed it in the documentation. The old screenshot will still be available in the git history but the engine doesn't exist any more.
